### ISSUE TITLE
question?

### ISSUE THREAD

**Issue by tashikuma** [LagradOst/PaladinsHackPublic#4]
hey! 
thank you so much for the Paladins hack, it works flawlessly for me, i've been using it since the day you posted the source!!
i was wondering if only using the glow feature will be detected or not?
 and is the cheat detected by hi-rez or the people who got banned got reported?

thank you! ^^

**Comment by LagradOst** [comment]
I have absolutely no idea what is detected, as I have never been banned in any Hi-Rez game. My guess is report or sig ban.

**Comment by tashikuma** [comment]
Thanks for the reply!
